# Generated by Django 5.2.14 on 2026-06-17 03:27

from django.core.validators import MinValueValidator
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="invoice_vault_slot_limit_per_project_chain",
            field=models.PositiveIntegerField(
                default=100,
                help_text="单个项目在单条链上最多可创建的账单收款 VaultSlot 数量。达到上限后仍可复用已有可用槽位，但不再创建新槽位。",
                validators=[MinValueValidator(1)],
                verbose_name="账单 VaultSlot 单项目单链上限",
            ),
        ),
    ]
