# Generated by Django 5.2.14 on 2026-07-06 08:12

from django.core import validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_systemsettings_vault_slot_collect_min_worth_usd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="evm_vault_slot_collect_delay_minutes",
            field=models.PositiveIntegerField(
                default=60,
                help_text="EVM 到账确认后等待该时间再聚合归集，期间同槽位同币种不重复创建归集计划。EVM 默认 60 分钟，兼顾到账归集时效和同槽位批量归集。",
                validators=[validators.MinValueValidator(0)],
                verbose_name="EVM VaultSlot 归集延迟(分钟)",
            ),
        ),
    ]
