# Generated by Django 5.2.14 on 2026-06-16 05:55

import common.fields
import django.db.models.deletion
import shortuuid.django_fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="23456789ABCDEFGHJKLMNPQRSTUVWXYZ",
                        db_index=True,
                        editable=False,
                        length=8,
                        max_length=11,
                        prefix="XC-",
                        unique=True,
                        verbose_name="Appid",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="对外作为商户名展示",
                        unique=True,
                        verbose_name="项目名称",
                    ),
                ),
                (
                    "ip_white_list",
                    models.TextField(
                        default="*",
                        help_text="只有符合白名单的 IP 才可以与本网关交互，支持 IP 地址或 IP 网段<br>可同时设置多个，中间用英文逗号 ',' 分割<br>* 代表允许所有 IP 访问",
                        verbose_name="IP白名单",
                    ),
                ),
                (
                    "webhook",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="用于本网关发送通知到商户后端",
                        verbose_name="通知地址",
                    ),
                ),
                (
                    "webhook_open",
                    models.BooleanField(default=True, verbose_name="通知状态"),
                ),
                (
                    "fast_confirm_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        help_text="低于该金额的账单收款无需等待区块确认数，立即确认",
                        max_digits=10,
                        verbose_name="快速确认阈值（USD）",
                    ),
                ),
                (
                    "hmac_key",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=32,
                        max_length=32,
                        prefix="",
                        verbose_name="HMAC密钥",
                    ),
                ),
                (
                    "evm_vault",
                    common.fields.AddressField(
                        blank=True,
                        db_index=True,
                        help_text="用于生成 EVM 智能合约收款地址的不可变归集地址，必须是 EVM checksum 地址。留空时禁止在 EVM 使用智能合约收款；一旦设置不可修改。",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="EVM 收款归集地址",
                    ),
                ),
                (
                    "tron_vault",
                    common.fields.AddressField(
                        blank=True,
                        db_index=True,
                        help_text="用于生成 Tron 智能合约收款地址的不可变归集地址，必须是 Tron Base58 地址。留空时禁止在 Tron 使用智能合约收款；一旦设置不可修改。",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Tron 收款归集地址",
                    ),
                ),
                (
                    "invoice_receiving_mode",
                    models.CharField(
                        choices=[("vault_slot", "智能合约"), ("differ", "钱包直收")],
                        default="differ",
                        help_text="项目级全局账单收款模式；某条链未单独设置覆盖时继承此模式。钱包直收无需链上归集交易，作为默认。",
                        verbose_name="账单收款模式",
                    ),
                ),
                (
                    "evm_invoice_receiving_mode",
                    models.CharField(
                        blank=True,
                        choices=[("vault_slot", "智能合约"), ("differ", "钱包直收")],
                        default="",
                        help_text="仅覆盖 EVM 链；留空则继承全局账单收款模式。",
                        verbose_name="EVM 账单收款模式覆盖",
                    ),
                ),
                (
                    "tron_invoice_receiving_mode",
                    models.CharField(
                        blank=True,
                        choices=[("vault_slot", "智能合约"), ("differ", "钱包直收")],
                        default="",
                        help_text="仅覆盖 Tron 链；留空则继承全局账单收款模式。",
                        verbose_name="Tron 账单收款模式覆盖",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "is_test",
                    models.BooleanField(
                        default=False,
                        help_text="测试项目只能使用测试网链（创建充值收款地址、账单收款仅限测试网）；非测试项目只能使用主网。用于隔离主网与测试网代币，防止混淆。",
                        verbose_name="测试项目",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, verbose_name="客户UID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("uid", "project"), name="uniq_customer_uid_project"
                    )
                ],
            },
        ),
    ]
