# Generated by Django 5.2.14 on 2026-06-14 02:34

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TronTxTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "to",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="To"
                    ),
                ),
                (
                    "function_selector",
                    models.CharField(max_length=128, verbose_name="函数签名"),
                ),
                (
                    "parameter",
                    models.TextField(blank=True, default="", verbose_name="ABI 参数"),
                ),
                ("fee_limit", models.PositiveBigIntegerField(verbose_name="Fee Limit")),
                (
                    "expiration",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="过期时间(ms)"
                    ),
                ),
                (
                    "ref_block_bytes",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=16,
                        verbose_name="Ref Block Bytes",
                    ),
                ),
                (
                    "ref_block_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Ref Block Hash",
                    ),
                ),
                (
                    "signed_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="已签名链上载荷"
                    ),
                ),
                (
                    "tx_id",
                    common.fields.HashField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=False,
                        verbose_name="当前 TxID",
                    ),
                ),
                (
                    "simulation_revert_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="模拟 Revert 连续次数"
                    ),
                ),
                (
                    "simulation_revert_first_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="模拟 Revert 首次观测时间"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次尝试时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "base_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tron_task",
                        to="chains.txtask",
                        verbose_name="通用链上任务",
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chains.chain",
                        verbose_name="网络",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chains.address",
                        verbose_name="发送地址",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tron 链上任务",
                "verbose_name_plural": "Tron 链上任务",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="TronWatchCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_scanned_block",
                    models.PositiveIntegerField(
                        default=0, verbose_name="已扫描到的区块"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "last_error",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="最近错误"
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近错误时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tron_watch_cursors",
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tron 扫描游标",
                "verbose_name_plural": "Tron 扫描游标",
                "ordering": ("chain_id",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chain",), name="uniq_tron_watch_cursor_chain"
                    )
                ],
            },
        ),
    ]
