# Generated by Django 5.2.14 on 2026-06-14 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
        ("currencies", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="crypto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="currencies.crypto",
                verbose_name="加密货币",
            ),
        ),
        migrations.AddField(
            model_name="txhash",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tx_hashes",
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="txtask",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="txtask",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chains.address",
                verbose_name="发送地址",
            ),
        ),
        migrations.AddField(
            model_name="txhash",
            name="tx_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tx_hashes",
                to="chains.txtask",
                verbose_name="链上任务",
            ),
        ),
        migrations.AddField(
            model_name="vaultslot",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="vaultslot",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.customer",
                verbose_name="客户",
            ),
        ),
        migrations.AddField(
            model_name="vaultslot",
            name="deploy_tx_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deployed_vault_slot",
                to="chains.txtask",
                verbose_name="部署交易任务",
            ),
        ),
        migrations.AddField(
            model_name="vaultslot",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="项目",
            ),
        ),
        migrations.CreateModel(
            name="DepositVaultSlot",
            fields=[],
            options={
                "verbose_name": "充值收款地址",
                "verbose_name_plural": "充值收款地址",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("chains.vaultslot",),
        ),
        migrations.CreateModel(
            name="InvoiceVaultSlot",
            fields=[],
            options={
                "verbose_name": "账单收款地址",
                "verbose_name_plural": "账单收款地址",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("chains.vaultslot",),
        ),
        migrations.AddField(
            model_name="vaultslotbalance",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="vaultslotbalance",
            name="crypto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="currencies.crypto",
                verbose_name="币种",
            ),
        ),
        migrations.AddField(
            model_name="vaultslotbalance",
            name="vault_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to="chains.vaultslot",
                verbose_name="收款地址",
            ),
        ),
        migrations.AddField(
            model_name="vaultslotcollectschedule",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="vaultslotcollectschedule",
            name="crypto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="currencies.crypto",
                verbose_name="币种",
            ),
        ),
        migrations.AddField(
            model_name="vaultslotcollectschedule",
            name="tx_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vault_slot_collect_schedule",
                to="chains.txtask",
                verbose_name="链上任务",
            ),
        ),
        migrations.AddField(
            model_name="vaultslotcollectschedule",
            name="vault_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collect_schedules",
                to="chains.vaultslot",
                verbose_name="收款地址",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.wallet",
                verbose_name="钱包",
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.UniqueConstraint(
                fields=("chain", "hash", "event_index"),
                name="uniq_transfer_chain_hash_event_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="txtask",
            constraint=models.UniqueConstraint(
                fields=("chain", "tx_hash"), name="uniq_tx_task_chain_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="txhash",
            constraint=models.UniqueConstraint(
                fields=("chain", "hash"), name="uniq_tx_hash_chain_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="txhash",
            constraint=models.UniqueConstraint(
                fields=("tx_task", "version"), name="uniq_tx_hash_task_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="vaultslot",
            constraint=models.UniqueConstraint(
                fields=("customer", "chain"), name="uniq_vault_slot_customer_chain"
            ),
        ),
        migrations.AddConstraint(
            model_name="vaultslot",
            constraint=models.UniqueConstraint(
                fields=("project", "usage", "chain", "invoice_index"),
                name="uniq_vault_slot_project_usage_chain_invoice_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="vaultslot",
            constraint=models.UniqueConstraint(
                fields=("chain", "address"), name="uniq_vault_slot_chain_address"
            ),
        ),
        migrations.AddConstraint(
            model_name="vaultslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("customer__isnull", False),
                        ("invoice_index__isnull", True),
                        ("usage", "deposit"),
                    ),
                    models.Q(
                        ("customer__isnull", True),
                        ("invoice_index__isnull", False),
                        ("usage", "invoice"),
                    ),
                    _connector="OR",
                ),
                name="ck_vault_slot_usage_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="vaultslotbalance",
            constraint=models.UniqueConstraint(
                fields=("chain", "vault_slot", "crypto"),
                name="uniq_vault_slot_balance_chain_slot_crypto",
            ),
        ),
        migrations.AddConstraint(
            model_name="vaultslotcollectschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tx_task__isnull", True)),
                fields=("chain", "vault_slot", "crypto"),
                name="uniq_pending_vault_slot_collect",
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                fields=("wallet", "chain_type", "usage", "address_index"),
                name="uniq_address_wallet_chain_usage_addridx",
            ),
        ),
    ]
