# Generated by Django 5.2.14 on 2026-06-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaultslotbalance",
            name="amount",
            field=models.DecimalField(
                decimal_places=8, default=0, max_digits=32, verbose_name="余额"
            ),
        ),
        migrations.AlterField(
            model_name="vaultslotbalance",
            name="value",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=32,
                verbose_name="链上最小单位余额",
            ),
        ),
        migrations.AlterField(
            model_name="vaultslotbalance",
            name="worth",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=32, verbose_name="价值(USD)"
            ),
        ),
    ]
