# Generated by Django 5.2.12 on 2026-05-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0011_rename_broadcasttask_transfer_type_action_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="broadcasttask",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="broadcasttask",
            name="crypto",
        ),
        migrations.RemoveField(
            model_name="broadcasttask",
            name="recipient",
        ),
    ]
