# Generated by Django 5.2.12 on 2026-05-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0012_remove_broadcasttask_amount_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Balance",
        ),
    ]
