# Generated by Django 5.2.12 on 2026-05-18 06:36

from django.db import migrations, models
from django_migration_linter.operations import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0015_remove_bitcoin_data"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        # 定点忽略 migration linter 的 ADD_UNIQUE 拦截：
        # 上线前已确认 chains_chain 中非 EVM type 不存在重复值。
        IgnoreMigration(),
        migrations.AlterField(
            model_name="address",
            name="chain_type",
            field=models.CharField(
                choices=[("evm", "EVM"), ("tron", "Tron")], verbose_name="链类型"
            ),
        ),
        migrations.AlterField(
            model_name="broadcasttask",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rpc_rejected", "节点拒绝"),
                    ("insufficient_balance", "余额不足"),
                    ("fee_too_low", "手续费过低"),
                    ("execution_reverted", "链上执行回退"),
                    ("expected_transfer_missing", "链上执行成功但预期资产移动缺失"),
                ],
                default="",
                max_length=64,
                verbose_name="失败原因",
            ),
        ),
        migrations.AlterField(
            model_name="chain",
            name="type",
            field=models.CharField(
                choices=[("evm", "EVM"), ("tron", "Tron")], verbose_name="类型"
            ),
        ),
        migrations.AddConstraint(
            model_name="chain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "evm"), _negated=True),
                fields=("type",),
                name="uniq_chain_type_for_non_evm",
            ),
        ),
    ]
