# Generated by Django 5.2.12 on 2026-05-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttelegramalertconfig",
            name="notify_on_contract_collection_stalled",
            field=models.BooleanField(default=True, verbose_name="合约归集卡单告警"),
        ),
        migrations.AlterField(
            model_name="projectalertstate",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("withdrawal_stalled", "提币卡单"),
                    ("deposit_collection_stalled", "归集卡单"),
                    ("contract_collection_stalled", "合约归集卡单"),
                    ("webhook_stalled", "Webhook 堆积"),
                ],
                max_length=64,
                verbose_name="事件类型",
            ),
        ),
    ]
